/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using SUSTech.Scape.ECG.RosBridgeClient.BaseMessages;

namespace SUSTech.Scape.ECG.RosBridgeClient.MessageTypes.Std.msg
{
    public class UInt8 : Message
    {
        public const string RosMessageName = "std_msgs/UInt8";

        public byte data { get; set; }

        public UInt8()
        {
            this.data = 0;
        }

        public UInt8(byte data)
        {
            this.data = data;
        }
    }
}
