(cl:in-package driver_ecg-msg)
(cl:export '(ROSTIME-VAL
          ROSTIME
          DATETIME-VAL
          DATETIME
          AVERAGEHEARTRATE-VAL
          AVERAGEHEARTRATE
          INSTANTANEOUSHEARTRATE-VAL
          INSTANTANEOUSHEARTRATE
          ELECTROCARDIOGRAM-VAL
          ELECTROCARDIOGRAM
))