// Generated by gencpp from file driver_ecg/Debug.msg
// DO NOT EDIT!


#ifndef DRIVER_ECG_MESSAGE_DEBUG_H
#define DRIVER_ECG_MESSAGE_DEBUG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace driver_ecg
{
template <class ContainerAllocator>
struct Debug_
{
  typedef Debug_<ContainerAllocator> Type;

  Debug_()
    : RosTime()
    , DateTime()
    , AverageHeartRate(0)
    , InstantaneousHeartRate(0)
    , Electrocardiogram()
    , CacheLength(0)
    , SequenceId(0)  {
    }
  Debug_(const ContainerAllocator& _alloc)
    : RosTime()
    , DateTime(_alloc)
    , AverageHeartRate(0)
    , InstantaneousHeartRate(0)
    , Electrocardiogram(_alloc)
    , CacheLength(0)
    , SequenceId(0)  {
  (void)_alloc;
    }



   typedef ros::Time _RosTime_type;
  _RosTime_type RosTime;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _DateTime_type;
  _DateTime_type DateTime;

   typedef int32_t _AverageHeartRate_type;
  _AverageHeartRate_type AverageHeartRate;

   typedef int32_t _InstantaneousHeartRate_type;
  _InstantaneousHeartRate_type InstantaneousHeartRate;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _Electrocardiogram_type;
  _Electrocardiogram_type Electrocardiogram;

   typedef int32_t _CacheLength_type;
  _CacheLength_type CacheLength;

   typedef uint64_t _SequenceId_type;
  _SequenceId_type SequenceId;





  typedef boost::shared_ptr< ::driver_ecg::Debug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::driver_ecg::Debug_<ContainerAllocator> const> ConstPtr;

}; // struct Debug_

typedef ::driver_ecg::Debug_<std::allocator<void> > Debug;

typedef boost::shared_ptr< ::driver_ecg::Debug > DebugPtr;
typedef boost::shared_ptr< ::driver_ecg::Debug const> DebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::driver_ecg::Debug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::driver_ecg::Debug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::driver_ecg::Debug_<ContainerAllocator1> & lhs, const ::driver_ecg::Debug_<ContainerAllocator2> & rhs)
{
  return lhs.RosTime == rhs.RosTime &&
    lhs.DateTime == rhs.DateTime &&
    lhs.AverageHeartRate == rhs.AverageHeartRate &&
    lhs.InstantaneousHeartRate == rhs.InstantaneousHeartRate &&
    lhs.Electrocardiogram == rhs.Electrocardiogram &&
    lhs.CacheLength == rhs.CacheLength &&
    lhs.SequenceId == rhs.SequenceId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::driver_ecg::Debug_<ContainerAllocator1> & lhs, const ::driver_ecg::Debug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace driver_ecg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::driver_ecg::Debug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::driver_ecg::Debug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver_ecg::Debug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver_ecg::Debug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver_ecg::Debug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver_ecg::Debug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::driver_ecg::Debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76c689e5f8091168cc6edafa3a989eae";
  }

  static const char* value(const ::driver_ecg::Debug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76c689e5f8091168ULL;
  static const uint64_t static_value2 = 0xcc6edafa3a989eaeULL;
};

template<class ContainerAllocator>
struct DataType< ::driver_ecg::Debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "driver_ecg/Debug";
  }

  static const char* value(const ::driver_ecg::Debug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::driver_ecg::Debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time RosTime\n"
"string DateTime\n"
"int32 AverageHeartRate\n"
"int32 InstantaneousHeartRate\n"
"int32[] Electrocardiogram\n"
"int32 CacheLength\n"
"uint64 SequenceId\n"
;
  }

  static const char* value(const ::driver_ecg::Debug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::driver_ecg::Debug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RosTime);
      stream.next(m.DateTime);
      stream.next(m.AverageHeartRate);
      stream.next(m.InstantaneousHeartRate);
      stream.next(m.Electrocardiogram);
      stream.next(m.CacheLength);
      stream.next(m.SequenceId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Debug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::driver_ecg::Debug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::driver_ecg::Debug_<ContainerAllocator>& v)
  {
    s << indent << "RosTime: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.RosTime);
    s << indent << "DateTime: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.DateTime);
    s << indent << "AverageHeartRate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.AverageHeartRate);
    s << indent << "InstantaneousHeartRate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.InstantaneousHeartRate);
    s << indent << "Electrocardiogram[]" << std::endl;
    for (size_t i = 0; i < v.Electrocardiogram.size(); ++i)
    {
      s << indent << "  Electrocardiogram[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.Electrocardiogram[i]);
    }
    s << indent << "CacheLength: ";
    Printer<int32_t>::stream(s, indent + "  ", v.CacheLength);
    s << indent << "SequenceId: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.SequenceId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVER_ECG_MESSAGE_DEBUG_H
